# Generated by Django 5.0.6 on 2024-06-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('cantidad_miembros', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'grupo_paciente',
                'verbose_name_plural': 'grupo_pacientes',
                'db_table': 'Grupo_Pacientes',
                'ordering': ['nombre'],
                'permissions': (('es_secretaria', 'Puede administrar'),),
            },
        ),
    ]
