# Generated by Django 5.0.6 on 2024-07-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0003_remove_grupo_pacientes_grupo_pacientes'),
        ('pacientes', '0003_paciente_id_alter_paciente_historia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='pacientes',
            field=models.ManyToManyField(related_name='pacientes', to='pacientes.paciente'),
        ),
    ]
