# Generated by Django 5.0.6 on 2024-07-07 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0005_alter_grupo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ['nombre'], 'permissions': (('es_secretaria', 'Puede administrar'),), 'verbose_name': 'grupo_paciente', 'verbose_name_plural': 'grupo_pacientes'},
        ),
    ]
