# Generated by Django 5.0.6 on 2024-06-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(choices=[('Alergia', 'Alergia'), ('Anatomia Patologica', 'AnatomPat'), ('Cirugia', 'Cirugia'), ('Geriatria', 'Geriatria'), ('Ginecob', 'Ginecob'), ('Imagenologia', 'Imag'), ('Lab_Clinico', 'Lab_Clinico'), ('Maxilofacial', 'Maxilofacial'), ('Med_Fis_Rehab', 'Med_Fis_Rehab'), ('Med_Interna', 'Med_Interna'), ('Med_Trabajo', 'Med_Trabajo'), ('Microbiologia', 'Microbiologia'), ('Nefrologia', 'Nefrologia'), ('Neurocirugia', 'Neurocirugia'), ('Neurologia', 'Neurologia'), ('Oftalmologia', 'Oftalmologia'), ('ORL', 'ORL'), ('Oncologia', 'Oncologia'), ('Ortopedia', 'Ortopedia'), ('Proctologia', 'Proctologia'), ('Psiquiatria', 'Psiquiatria'), ('Quemado', 'Quemado'), ('Urologia', 'Urologia'), ('Reumatologia', 'Reumatologia'), ('Vias_digestivas', 'VDigest')], max_length=255)),
                ('enfermedad', models.TextField(max_length=450)),
                ('sintomas', models.TextField(max_length=255)),
                ('estado', models.CharField(choices=[('Grave', 'Grave'), ('Levemente grave', 'Levemente Grave')], max_length=30)),
            ],
            options={
                'verbose_name': 'diagnostico',
                'verbose_name_plural': 'diagnosticos',
                'db_table': 'Diagnostico',
                'ordering': ['especialidad'],
                'permissions': (('es_doctor', 'Puede administrar'),),
            },
        ),
    ]
