# Generated by Django 5.0.6 on 2024-07-06 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosticos', '0001_initial'),
        ('pacientes', '0002_alter_paciente_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='paciente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paciente', to='pacientes.paciente'),
        ),
    ]
