# Generated by Django 5.0.6 on 2024-07-06 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosticos', '0002_diagnostico_paciente'),
        ('pacientes', '0002_alter_paciente_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='enfermedad',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='paciente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='sintomas',
            field=models.TextField(max_length=450),
        ),
    ]
