# Generated by Django 5.0.6 on 2024-07-07 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosticos', '0003_alter_diagnostico_enfermedad_and_more'),
        ('pacientes', '0004_alter_paciente_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='paciente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paciente', to='pacientes.paciente'),
        ),
    ]
