# Generated by Django 5.0.6 on 2024-07-09 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosticos', '0006_alter_diagnostico_options'),
        ('pacientes', '0007_alter_paciente_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='paciente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paciente', to='pacientes.paciente'),
        ),
    ]
