# Generated by Django 5.0.6 on 2024-06-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('historia', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('ci', models.CharField(max_length=11, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('edad', models.PositiveIntegerField()),
                ('sexo', models.CharField(max_length=10)),
                ('direccion', models.CharField(blank=True, max_length=60)),
                ('area_de_salud', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True)),
                ('tratamiento', models.CharField(choices=[('Medico', 'Medico'), ('Alta', 'Alta'), ('Estudio', 'Estudio'), ('Quirurgico', 'Quirurgico'), ('Urgencia', 'Urgencia')], default='Medico', max_length=25)),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
                'db_table': 'Paciente',
                'ordering': ['historia'],
                'permissions': (('es_secretaria', 'Puede administrar'),),
            },
        ),
    ]
