# Generated by Django 5.0.6 on 2024-07-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F'), ('Otro', 'Otro')], max_length=10),
        ),
    ]
