# Generated by Django 5.0.6 on 2024-07-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_paciente_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='id',
            field=models.BigIntegerField(default=True, max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='historia',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
