# Generated by Django 5.0.6 on 2024-07-07 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_alter_paciente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['historia'], 'permissions': (('es_secretaria', 'Puede administrar'),), 'verbose_name': 'paciente', 'verbose_name_plural': 'pacientes'},
        ),
    ]
